/*
 * Copyright 2026 Magnus Madsen, Werner Stein
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ca.uwaterloo.flix

import ca.uwaterloo.flix.api.{CompilerConstants, Flix}
import ca.uwaterloo.flix.language.ast.Symbol
import ca.uwaterloo.flix.language.ast.shared.SecurityContext
import ca.uwaterloo.flix.util.{LibLevel, Options, Result}
import org.objectweb.asm.{ClassReader, ClassVisitor, MethodVisitor, Opcodes}
import org.scalatest.Assertions

import scala.collection.mutable

/**
  * Support for asserting what a compiled program can and cannot reach.
  *
  * Tests that assert the *absence* of something must also assert its presence in a build where it
  * is expected, since an assertion that never had anything to find is indistinguishable from a
  * successful erasure. Note also that the program under test must be effectful and must consume
  * its result, or it is eliminated as dead code before any of this becomes observable.
  */
trait BytecodeInspection extends Assertions {

  import BytecodeInspection.Bytecode

  /**
    * Compiles `program` under `options` and returns the generated bytecode.
    *
    * The entry point is assumed to be `main`.
    */
  def compileAndScan(program: String, options: Options): Bytecode = {
    val opts = options.copy(
      lib = LibLevel.All,
      entryPoint = Some(Symbol.mkDefnSym("main"))
    )
    val flix = new Flix().setOptions(opts)
    implicit val sctx: SecurityContext = SecurityContext.Unrestricted
    flix.addVirtualPath(CompilerConstants.VirtualTestFile, program)

    val compilationResult = flix.compile() match {
      case Result.Ok(result) => result
      case Result.Err(errors) => fail(s"Expected a successful compilation, got: $errors")
    }

    val classes = mutable.Set.empty[String]
    val calls = mutable.Set.empty[(String, String, String)]

    assert(compilationResult.getClasses.nonEmpty, "No classes were generated.")
    for (clazz <- compilationResult.getClasses.values) {
      val reader = new ClassReader(clazz.bytecode)
      var current = ""
      reader.accept(new ClassVisitor(Opcodes.ASM9) {
        override def visit(version: Int, access: Int, name: String, signature: String, superName: String, interfaces: Array[String]): Unit = {
          current = name
          classes += name
          super.visit(version, access, name, signature, superName, interfaces)
        }

        override def visitMethod(access: Int, name: String, descriptor: String, signature: String, exceptions: Array[String]): MethodVisitor = {
          val caller = current
          new MethodVisitor(Opcodes.ASM9, super.visitMethod(access, name, descriptor, signature, exceptions)) {
            override def visitMethodInsn(opcode: Int, owner: String, methodName: String, descriptor: String, isInterface: Boolean): Unit = {
              calls += ((caller, owner, methodName))
              super.visitMethodInsn(opcode, owner, methodName, descriptor, isInterface)
            }
          }
        }
      }, 0)
    }

    Bytecode(classes.toSet, calls.toSet)
  }
}

object BytecodeInspection {

  /**
    * The generated bytecode of a whole program, reduced to what the tests reason about.
    *
    * `classes` holds the internal name of every generated class. `calls` holds triples of
    * (calling class, callee owner, callee method).
    */
  case class Bytecode(classes: Set[String], calls: Set[(String, String, String)]) {

    /**
      * Returns the classes generated for the definition named `name` in `namespace`, and for its
      * closures.
      *
      * The backend emits one class per specialization, named `Def$<name>$<id>` (and
      * `Clo$<name>$<id>` for closures), so the lookup is by prefix rather than by exact name.
      */
    def classesOfDef(namespace: String, name: String): Set[String] =
      classes.filter(c => c.startsWith(s"$namespace/Def$$$name$$") || c.startsWith(s"$namespace/Clo$$$name$$"))

    /**
      * Returns the classes generated for `namespace` and everything nested inside it.
      */
    def classesOfNamespace(namespace: String): Set[String] =
      classes.filter(c => c == namespace || c.startsWith(namespace + "/"))

    /**
      * Returns the thread-spawning call sites, optionally restricted to `namespace`.
      *
      * A `spawn` into a dynamic region compiles to `Region.spawn`, whereas a `spawn` at the
      * `Static` region compiles to `Thread.startVirtualThread`. Both are matched.
      */
    def spawnSites(namespace: Option[String] = None): Set[(String, String, String)] =
      calls.filter {
        case (caller, owner, name) =>
          namespace.forall(ns => caller.startsWith(ns + "/")) &&
            ((owner == "dev/flix/runtime/Region$" && name == "spawn") || name == "startVirtualThread")
      }

    /**
      * Returns the names of the definitions in `namespace` that spawn a thread into a dynamic
      * region.
      */
    def regionSpawningDefsIn(namespace: String): Set[String] =
      spawnSites(Some(namespace)).collect { case (caller, _, "spawn") => defNameOf(caller) }

    /**
      * Returns the names of the definitions in `namespace` that spawn a virtual thread directly.
      */
    def virtualThreadSpawningDefsIn(namespace: String): Set[String] =
      spawnSites(Some(namespace)).collect { case (caller, _, "startVirtualThread") => defNameOf(caller) }
  }

  /**
    * Returns the source-level definition name encoded in the generated class name `clazz`.
    *
    * For example, `Fixpoint3/Interpreter/Def$interpret$1234` yields `interpret`.
    */
  def defNameOf(clazz: String): String =
    clazz.split('/').last.split('$') match {
      case Array(_, name, _*) => name
      case _ => clazz
    }
}
