/*
 * Copyright 2026 Magnus Madsen, Werner Stein
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ca.uwaterloo.flix.language.phase

import ca.uwaterloo.flix.TestUtils
import ca.uwaterloo.flix.api.{CompilerConstants, Flix}
import ca.uwaterloo.flix.language.ast.Symbol
import ca.uwaterloo.flix.language.ast.shared.SecurityContext
import ca.uwaterloo.flix.util.{ExecutionMode, LibLevel, Options, Result}
import org.objectweb.asm.{ClassReader, ClassVisitor, MethodVisitor, Opcodes}
import org.scalatest.funsuite.AnyFunSuite

import scala.collection.mutable

class TestDatalogReachability extends AnyFunSuite with TestUtils {

  ///
  /// A Datalog program whose result is observable.
  ///
  /// Note: `main` must be effectful and must actually consume the query result. If it is pure and
  /// discards the result, then the whole fixpoint computation is dead code and is eliminated in
  /// *both* modes, which makes every erasure assertion below vacuously true.
  ///
  private val DatalogProgram =
    """
      |def main(): Unit \ IO = {
      |    let p = #{
      |        Edge(1, 2).
      |        Edge(2, 3).
      |        Edge(3, 4).
      |        Path(x, y) :- Edge(x, y).
      |        Path(x, z) :- Path(x, y), Edge(y, z).
      |    };
      |    let res = solve p;
      |    let q = query res select (x, y) from Path(x, y);
      |    println(Vector.length(q))
      |}
    """.stripMargin

  ///
  /// The namespace holding the RAM interpreter.
  ///
  private val Interpreter = "Fixpoint3/Interpreter"

  ///
  /// The defs that implement parallel Datalog evaluation. None of these may survive in sequential
  /// mode, and all of them must survive in parallel mode.
  ///
  private val ParallelDefs = List(
    "evalStmtParallel",
    "evalOpParallel",
    "evalSearchOrQueryOpParallel",
    "evalSearchOrQueryOpLatticeParallel",
    "parEvalSearchOrQueryOp",
    "parEvalSearchOrQueryOpLattice",
    "copyCtx"
  )

  ///
  /// The defs that implement sequential Datalog evaluation. These must survive in sequential mode
  /// and must be absent in parallel mode.
  ///
  private val SequentialDefs = List(
    "evalStmtSequential",
    "evalOpSequential",
    "evalSearchOrQueryOpSequential",
    "evalSearchOrQueryOpLatticeSequential"
  )

  ///
  /// The generated bytecode of a whole program, reduced to what this test reasons about.
  ///
  /// `classes` holds the internal name of every generated class. `calls` holds triples of
  /// (calling class, callee owner, callee method).
  ///
  private case class Bytecode(classes: Set[String], calls: Set[(String, String, String)]) {

    /**
      * Returns the classes generated for the def named `name` in `namespace`, and for its closures.
      *
      * The backend emits one class per specialization, named `Def$<name>$<id>` (and
      * `Clo$<name>$<id>` for closures), so the lookup is by prefix rather than by exact name.
      */
    def classesOfDef(namespace: String, name: String): Set[String] =
      classes.filter(c => c.startsWith(s"$namespace/Def$$$name$$") || c.startsWith(s"$namespace/Clo$$$name$$"))

    /**
      * Returns the thread-spawning call sites located in classes belonging to `namespace`.
      *
      * A `spawn` into a dynamic region compiles to `Region.spawn`, whereas a `spawn` at the
      * `Static` region compiles to `Thread.startVirtualThread`. Both are matched.
      */
    def spawnSitesIn(namespace: String): Set[(String, String, String)] =
      calls.filter {
        case (caller, owner, name) =>
          caller.startsWith(namespace + "/") &&
            ((owner == "dev/flix/runtime/Region$" && name == "spawn") || name == "startVirtualThread")
      }

    /**
      * Returns the names of the defs in `namespace` that spawn a thread into a dynamic region.
      *
      * This is the form the interpreter's own parallelism takes: `RamStmt.Par` spawns into the
      * region `rc2`, and `BPlusTree.parForEach` spawns into a region of its own.
      */
    def regionSpawningDefsIn(namespace: String): Set[String] =
      spawnSitesIn(namespace).collect { case (caller, _, "spawn") => defNameOf(caller) }

    /**
      * Returns the names of the defs in `namespace` that spawn a virtual thread directly.
      *
      * This is the form a `spawn ... @ Static` takes, which the interpreter never writes itself.
      */
    def virtualThreadSpawningDefsIn(namespace: String): Set[String] =
      spawnSitesIn(namespace).collect { case (caller, _, "startVirtualThread") => defNameOf(caller) }
  }

  /**
    * Returns the source-level def name encoded in the generated class name `clazz`.
    *
    * For example, `Fixpoint3/Interpreter/Def$interpret$1234` yields `interpret`.
    */
  private def defNameOf(clazz: String): String =
    clazz.split('/').last.split('$') match {
      case Array(_, name, _*) => name
      case _ => clazz
    }

  /**
    * Compiles [[DatalogProgram]] under `mode` and returns the generated bytecode.
    */
  private def compileAndScan(mode: ExecutionMode): Bytecode = {
    val options = Options.Default.copy(
      lib = LibLevel.All,
      xdatalogExecution = mode,
      entryPoint = Some(Symbol.mkDefnSym("main"))
    )
    val flix = new Flix().setOptions(options)
    implicit val sctx: SecurityContext = SecurityContext.Unrestricted
    flix.addVirtualPath(CompilerConstants.VirtualTestFile, DatalogProgram)

    val compilationResult = flix.compile() match {
      case Result.Ok(result) => result
      case Result.Err(errors) => fail(s"Expected successful compilation under mode $mode, got: $errors")
    }

    val classes = mutable.Set.empty[String]
    val calls = mutable.Set.empty[(String, String, String)]

    assert(compilationResult.getClasses.nonEmpty, s"No classes were generated under mode $mode.")
    for (clazz <- compilationResult.getClasses.values) {
      val reader = new ClassReader(clazz.bytecode)
      var current = ""
      reader.accept(new ClassVisitor(Opcodes.ASM9) {
        override def visit(version: Int, access: Int, name: String, signature: String, superName: String, interfaces: Array[String]): Unit = {
          current = name
          classes += name
          super.visit(version, access, name, signature, superName, interfaces)
        }

        override def visitMethod(access: Int, name: String, descriptor: String, signature: String, exceptions: Array[String]): MethodVisitor = {
          val caller = current
          new MethodVisitor(Opcodes.ASM9, super.visitMethod(access, name, descriptor, signature, exceptions)) {
            override def visitMethodInsn(opcode: Int, owner: String, methodName: String, descriptor: String, isInterface: Boolean): Unit = {
              calls += ((caller, owner, methodName))
              super.visitMethodInsn(opcode, owner, methodName, descriptor, isInterface)
            }
          }
        }
      }, 0)
    }

    Bytecode(classes.toSet, calls.toSet)
  }

  /// The two builds under comparison. They are scanned once and shared by the tests below.
  ///
  /// Only `xdatalogExecution` differs, so that everything observed here is attributable to it.
  ///
  private lazy val ParallelBuild: Bytecode = compileAndScan(ExecutionMode.Parallel)

  private lazy val SequentialBuild: Bytecode = compileAndScan(ExecutionMode.Sequential)

  ///
  /// The positive control for the erasure test below.
  ///
  /// Every erasure asserted below is only meaningful if the very same construct is present in a
  /// parallel build. Without this test, an assertion that never had anything to find would be
  /// indistinguishable from a successful erasure.
  ///
  test("Reachability.ParallelMode.RetainsParallelConstructs") {
    val res = ParallelBuild

    for (name <- ParallelDefs) {
      assert(res.classesOfDef(Interpreter, name).nonEmpty, s"Expected '$name' to be present in a parallel build.")
    }
    for (name <- SequentialDefs) {
      assert(res.classesOfDef(Interpreter, name).isEmpty, s"Expected '$name' to be absent from a parallel build.")
    }

    // Both kinds of parallelism must be present: statement parallelism (`RamStmt.Par`, spawned by
    // `evalStmtParallel`) and search parallelism (`BPlusTree.parForEach`, which the inliner folds
    // into `evalOpParallel`, so it is identified by its spawn site rather than by its own class).
    val spawns = res.regionSpawningDefsIn(Interpreter)
    assert(spawns.contains("evalStmtParallel"), s"Expected statement parallelism in a parallel build, but found: $spawns")
    assert(spawns.contains("evalOpParallel"), s"Expected search parallelism in a parallel build, but found: $spawns")
  }

  test("Reachability.SequentialMode.ErasesParallelConstructs") {
    val res = SequentialBuild

    // 1. The parallel evaluator family is gone, and the sequential one has taken its place.
    for (name <- ParallelDefs) {
      assert(res.classesOfDef(Interpreter, name).isEmpty, s"Found reachable '$name': ${res.classesOfDef(Interpreter, name)}")
    }
    for (name <- SequentialDefs) {
      assert(res.classesOfDef(Interpreter, name).nonEmpty, s"Expected '$name' to be present in a sequential build.")
    }

    // 2. Neither statement parallelism nor search parallelism spawns threads any more.
    val spawns = res.regionSpawningDefsIn(Interpreter)
    assert(spawns.isEmpty, s"Found a reachable region spawn in the interpreter, in: $spawns")
  }

  ///
  /// Checks the interpreter's own bytecode rather than the absence of the parallel def names.
  ///
  /// The absence of a symbol is weaker than the absence of its body: the inliner can fold a def
  /// into its caller, so `evalStmtParallel` could disappear as a class while its body lives on
  /// inside `interpret`. This test therefore compares the spawn call sites of the two builds
  /// directly.
  ///
  test("Reachability.InterpreterSpawnSites.DifferOnlyInTheParallelEvaluator") {
    // 1. Spawning into a dynamic region is how the interpreter expresses its own parallelism:
    //    `RamStmt.Par` spawns into `rc2`, and `BPlusTree.parForEach` spawns into a region of its
    //    own. The parallel build must have such sites and the sequential build must have none,
    //    wherever the inliner happened to place the code.
    val parallelRegionSpawns = ParallelBuild.regionSpawningDefsIn(Interpreter)
    val sequentialRegionSpawns = SequentialBuild.regionSpawningDefsIn(Interpreter)
    assert(parallelRegionSpawns.nonEmpty, "Expected the interpreter to spawn into a region in a parallel build.")
    assert(
      sequentialRegionSpawns.isEmpty,
      s"The interpreter still spawns into a region in a sequential build, in: $sequentialRegionSpawns. " +
        s"If this names a def that is not part of the parallel evaluator, the parallel body was inlined " +
        s"into it and the dispatch on 'enableParallelExecution' was not folded away."
    )

    // 2. A `spawn ... @ Static` compiles to `Thread.startVirtualThread`. The interpreter never
    //    writes one; the sites that do appear come from `par (...) yield` in `RedBlackTree`,
    //    reached through the `@ParallelWhenPure` operations on `Map` that the interpreter uses to
    //    build and marshal its indexes. Removing those is the job of `--Xcollection-execution`,
    //    which is not varied here, so they are expected to survive -- but only identically in both
    //    builds. A site that exists in the sequential build and not in the parallel one could only
    //    come from the erased evaluator.
    val parallelVirtualSpawns = ParallelBuild.virtualThreadSpawningDefsIn(Interpreter)
    val sequentialVirtualSpawns = SequentialBuild.virtualThreadSpawningDefsIn(Interpreter)
    assert(
      sequentialVirtualSpawns.subsetOf(parallelVirtualSpawns),
      s"The sequential build spawns virtual threads in ${sequentialVirtualSpawns -- parallelVirtualSpawns}, " +
        s"which the parallel build does not. Sequential mode can only remove parallelism, never add it."
    )
  }
}
