/*
 * Copyright 2026 Werner Stein
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ca.uwaterloo.flix.language.phase

import ca.uwaterloo.flix.api.{CompilerConstants, Flix}
import ca.uwaterloo.flix.language.CompilationMessage
import ca.uwaterloo.flix.language.ast.shared.SecurityContext
import ca.uwaterloo.flix.tools.pkg.PackageModules
import ca.uwaterloo.flix.util.{Formatter, Options}
import org.scalatest.funsuite.AnyFunSuite

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}

/**
  * Tests the Markdown documentation backend.
  *
  * The assertions are structural rather than a comparison against a checked-in page: the standard
  * library's documentation comments change constantly, and a test that has to be regenerated after
  * every such change stops being read. What must hold is that a page names what it documents,
  * states its conventions truthfully, and drops nothing supported by the shared document model (`Documentor`).
  * Note: `struct` definitions and restrictable enums are omitted upstream by `Documentor.build`.
  */
class TestMarkdownDocumentor extends AnyFunSuite {

  private implicit val sctx: SecurityContext = SecurityContext.Unrestricted

  private def withTempDir[A](body: Path => A): A = {
    val dir = Files.createTempDirectory("flix-doc-")
    try {
      body(dir)
    } finally {
      deleteRecursively(dir)
    }
  }

  private def deleteRecursively(path: Path): Unit = {
    if (Files.isDirectory(path)) {
      import scala.util.Using
      Using(Files.list(path)) { stream =>
        stream.forEach(deleteRecursively)
      }
    }
    Files.deleteIfExists(path)
  }

  /** Returns the Markdown pages of `input`, which must compile without errors. */
  private def document(input: String,
                       packageModules: PackageModules = PackageModules.All,
                       options: Options = Options.TestWithLibNix): Map[String, String] = {
    implicit val flix: Flix = new Flix().setOptions(options)
    flix.addVirtualPath(CompilerConstants.VirtualTestFile, input)
    flix.check() match {
      case (Some(root), Nil) => MarkdownDocumentor.documentAll(root, packageModules)
      case (_, errors) => fail(CompilationMessage.formatAll(errors)(Formatter.NoFormatter, None))
    }
  }


  /** Writes the Markdown pages of `input` under `outputPath`, which must compile without errors. */
  private def generate(input: String, outputPath: Path): Unit = {
    implicit val flix: Flix = new Flix().setOptions(Options.TestWithLibNix.copy(outputPath = outputPath))
    flix.addVirtualPath(CompilerConstants.VirtualTestFile, input)
    flix.check() match {
      case (Some(root), Nil) => Documentor.run(root, PackageModules.All, ca.uwaterloo.flix.util.DocFormat.Markdown)
      case (_, errors) => fail(CompilationMessage.formatAll(errors)(Formatter.NoFormatter, None))
    }
  }

  /** Returns the page named `name`, failing if it was not generated. */
  private def page(pages: Map[String, String], name: String): String =
    pages.getOrElse(name, fail(s"expected a page '$name', but got: ${pages.keys.toList.sorted.mkString(", ")}"))

  test("page.enum.01") {
    val pages = document(
      """
        |///
        |/// A colour.
        |///
        |pub enum Color[t] {
        |    case Red
        |    case Custom(t)
        |}
        |""".stripMargin)

    val md = page(pages, "Color.md")
    assert(md.startsWith("<!-- Generated by the Flix compiler. Do not edit. -->\n\n# Color\n"), md)
    assert(md.contains("A colour."))
  }

  test("page.enum.02") {
    // The declaration must be valid Flix, braces and all, since the page is read to write code.
    val pages = document(
      """
        |pub enum Color[t] {
        |    case Red
        |    case Custom(t)
        |}
        |""".stripMargin)

    val md = page(pages, "Color.md")
    assert(md.contains("```flix\nenum Color[t: Type] {\n    case Red\n    case Custom(t)\n}\n```"), md)
  }

  test("page.enum.03") {
    // Derived traits belong on the declaration line, where they are in the source.
    val pages = document(
      """
        |pub enum Color with Eq {
        |    case Red
        |}
        |""".stripMargin, options = Options.TestWithLibMin)

    assert(page(pages, "Color.md").contains("enum Color with Eq {"))
  }

  test("page.instances.01") {
    // Every instance is listed and the count matches. Nothing is truncated.
    val pages = document(
      """
        |pub enum Box[a] {
        |    case Box(a)
        |}
        |
        |pub trait Describe[a] {
        |    pub def describe(x: a): String
        |}
        |
        |pub trait Render[a] {
        |    pub def render(x: a): String
        |}
        |
        |instance Describe[Box[a]] with Describe[a] {
        |    pub def describe(_x: Box[a]): String = "box"
        |}
        |
        |instance Render[Box[a]] {
        |    pub def render(_x: Box[a]): String = "box"
        |}
        |""".stripMargin)

    val md = page(pages, "Box.md")
    assert(md.contains("## Instances"))
    assert(md.contains("`Describe[Box[a]] with Describe[a]` ([Describe](Describe.md))"), md)
    assert(md.contains("`Render[Box[a]]` ([Render](Render.md))"), md)
    assert(md.contains("*(2 total)*"), md)
  }

  test("page.instances.02") {
    // On a trait's own page a link back to that same page would say nothing, so it is left out.
    val pages = document(
      """
        |pub trait Describe[a] {
        |    pub def describe(x: a): String
        |}
        |
        |instance Describe[Int32] {
        |    pub def describe(_x: Int32): String = "int"
        |}
        |""".stripMargin)

    val md = page(pages, "Describe.md")
    assert(md.contains("`Describe[Int32]` *(1 total)*"), md)
    assert(!md.contains("(Describe.md)"), "a trait page must not link to itself")
  }

  test("page.def.01") {
    // A signature carries parameters, return type, effect, and constraints.
    val pages = document(
      """
        |mod Api {
        |    ///
        |    /// Prints `x`.
        |    ///
        |    pub def show(x: a): Unit \ IO with ToString[a] = println(x)
        |}
        |""".stripMargin, options = Options.TestWithLibMin)

    val md = page(pages, "Api.md")
    assert(md.contains("`def show(x: a): Unit \\ IO with ToString[a]` — Prints `x`."), md)
  }

  test("page.def.02") {
    // A definition without parameters must not show the unit parameter the compiler introduces.
    val pages = document(
      """
        |mod Api {
        |    pub def zero(): Int32 = 0
        |}
        |""".stripMargin)

    assert(page(pages, "Api.md").contains("`def zero(): Int32`"))
  }

  test("page.def.03") {
    // Annotations change how a definition may be called, so they must survive onto the page.
    val pages = document(
      """
        |mod Api {
        |    @Lazy
        |    pub def delay(x: a): a = x
        |}
        |""".stripMargin)

    assert(page(pages, "Api.md").contains("`@Lazy def delay(x: a): a`"))
  }

  test("doc.summary.01") {
    // The first paragraph is collapsed onto the signature line; the rest follows verbatim.
    val pages = document(
      """
        |mod Api {
        |    ///
        |    /// Returns one.
        |    /// Always.
        |    ///
        |    /// Some more detail.
        |    ///
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    val md = page(pages, "Api.md")
    assert(md.contains("`def one(): Int32` — Returns one. Always."), md)
    assert(md.contains("Some more detail."), md)
  }

  test("doc.summary.02") {
    // A fenced example cannot be collapsed onto one line without destroying it.
    val pages = document(
      """
        |mod Api {
        |    ///
        |    /// Returns one.
        |    ///
        |    /// ```
        |    /// Api.one()
        |    /// ```
        |    ///
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    val md = page(pages, "Api.md")
    assert(md.contains("`def one(): Int32` — Returns one."), md)
    assert(md.contains("```\nApi.one()\n```"), md)
  }

  test("doc.summary.03") {
    // A list directly under the first line is not prose and must not be joined onto it.
    val pages = document(
      """
        |mod Api {
        |    ///
        |    /// Returns one, because:
        |    /// - it is one
        |    /// - it is not two
        |    ///
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    val md = page(pages, "Api.md")
    assert(md.contains("`def one(): Int32` — Returns one, because:"), md)
    assert(md.contains("- it is one\n- it is not two"), md)
  }

  test("doc.summary.04") {
    // A definition without documentation still gets a line of its own.
    val pages = document(
      """
        |mod Api {
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    assert(page(pages, "Api.md").contains("`def one(): Int32`\n"))
  }

  test("header.source.01") {
    // Everything on this page comes from one file, so the page may name it.
    val pages = document(
      """
        |mod Api {
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    assert(page(pages, "Api.md").contains(s"> Source: every definition lives in `${CompilerConstants.VirtualTestFile}`"))
  }

  test("header.source.02") {
    // A module with nothing but submodules has no definitions, so it must claim no source.
    val pages = document(
      """
        |mod Outer.Inner {
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    assert(!page(pages, "Outer.md").contains("> Source:"), "a page with no definitions must not name a source file")
  }

  test("header.crossref.01") {
    val pages = document("pub def one(): Int32 = 1")
    // The promise a page makes about where to find things must be one it can keep.
    val index = page(pages, "index.md")
    assert(index.contains("> Cross-references: each page is named after the fully qualified item it documents"), index)
    assert(index.contains("`Util.Json.ToJson.md`"), index)
  }

  test("index.01") {
    // The index backs the cross-reference promise by listing every page that exists.
    val pages = document(
      """
        |pub enum Color {
        |    case Red
        |}
        |
        |mod Api {
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    val index = page(pages, "index.md")
    assert(index.contains("## All Pages"))
    assert(index.contains("[Color](Color.md)"), index)
    assert(index.contains("[Api](Api.md)"), index)
    assert(index.contains("[index](index.md)"), index)
  }

  test("page.companion.01") {
    // A companion module has no page of its own; its definitions appear on the enum's page.
    val pages = document(
      """
        |pub enum Color {
        |    case Red
        |}
        |
        |mod Color {
        |    pub def isRed(c: Color): Bool = match c {
        |        case Color.Red => true
        |    }
        |}
        |""".stripMargin)

    val md = page(pages, "Color.md")
    assert(md.contains("## Definitions"))
    assert(md.contains("`def isRed(c: Color): Bool`"), md)
  }

  test("page.trait.01") {
    // Signatures and defaulted trait definitions are kept apart, as they are in the source.
    val pages = document(
      """
        |pub trait Greet[a] {
        |    pub def name(x: a): String
        |    pub def greet(_x: a): String = "hello"
        |}
        |""".stripMargin)

    val md = page(pages, "Greet.md")
    assert(md.contains("```flix\ntrait Greet[a: Type]\n```"), md)
    assert(md.contains("## Signatures\n\n`def name(x: a): String with Greet[a]`"), md)
    assert(md.contains("## Trait Definitions\n\n`def greet(_x: a): String with Greet[a]`"), md)
  }

  test("page.effect.01") {
    val pages = document(
      """
        |pub eff Ask {
        |    def ask(): String
        |}
        |""".stripMargin)

    val md = page(pages, "Ask.md")
    assert(md.contains("```flix\neff Ask\n```"), md)
    assert(md.contains("## Operations\n\n`def ask(): String \\ Ask`"), md)
  }

  test("page.typeAlias.01") {
    val pages = document(
      """
        |mod Api {
        |    ///
        |    /// A name.
        |    ///
        |    pub type alias Name = String
        |}
        |""".stripMargin)

    assert(page(pages, "Api.md").contains("`type alias Name = String` — A name."))
  }

  test("page.modules.01") {
    // A module page links to everything nested inside it, so the tree can be walked from the index.
    val pages = document(
      """
        |mod Outer {
        |    pub def one(): Int32 = 1
        |
        |    mod Inner {
        |        pub def two(): Int32 = 2
        |    }
        |}
        |""".stripMargin)

    assert(page(pages, "Outer.md").contains("## Modules\n\n- [Inner](Outer.Inner.md)"), page(pages, "Outer.md"))
    assert(pages.contains("Outer.Inner.md"))
  }

  test("page.private.01") {
    // Non-public items are not part of the API and must not appear on any page.
    val pages = document(
      """
        |mod Api {
        |    pub def visible(): Int32 = hidden()
        |    def hidden(): Int32 = 2
        |}
        |""".stripMargin)

    val md = page(pages, "Api.md")
    assert(md.contains("`def visible(): Int32`"))
    assert(!md.contains("hidden"), "a non-public definition must not be documented")
  }

  test("link.integrity.01") {
    // Every generated link must point at a page that was generated. A link to a page that does
    // not exist tells a reader something is documented when it is not.
    val pages = document(
      """
        |mod Api {
        |    pub enum Box[a] {
        |        case Box(a)
        |    }
        |
        |    trait Hidden[a] {
        |        pub def hidden(x: a): String
        |    }
        |
        |    instance Hidden[Box[a]] {
        |        pub def hidden(_x: Box[a]): String = "box"
        |    }
        |}
        |""".stripMargin)

    val md = page(pages, "Api.Box.md")
    // The instance is real API surface, so it is listed -- but `Hidden` is not public and has no page.
    assert(md.contains("`Hidden[Box[a]]` *(1 total)*"), md)
    assert(!md.contains("Hidden.md"), s"linked to a page that was never generated:\n$md")
    assert(!pages.contains("Api.Hidden.md"), pages.keys.toList.sorted.mkString(", "))
  }

  test("link.integrity.02") {
    // The same must hold across the whole standard library, which is where this first went wrong.
    val pages = document("pub def one(): Int32 = 1", options = Options.TestWithLibAll)

    val Link = """\]\(([A-Za-z0-9._]+\.md)\)""".r
    val broken = pages.values
      .flatMap(Link.findAllMatchIn(_).map(_.group(1)))
      .filterNot(pages.contains)
      .toList.distinct.sorted

    assert(broken.isEmpty, s"links to pages that do not exist: ${broken.mkString(", ")}")
  }

  test("link.integrity.03") {
    // A qualified item lives at its qualified name, which is what the preamble now promises.
    val pages = document(
      """
        |mod Outer.Inner {
        |    pub enum Color {
        |        case Red
        |    }
        |}
        |""".stripMargin)

    assert(pages.contains("Outer.Inner.Color.md"), pages.keys.toList.sorted.mkString(", "))
  }

  test("page.trait.03") {
    // A default makes the associated type optional for an implementor, so it must be shown.
    val pages = document(
      """
        |pub trait Wrap[a] {
        |    pub type Aef: Eff = {}
        |    pub def unwrap(x: a): a \ Wrap.Aef[a]
        |}
        |""".stripMargin)

    // `Pure` is how the compiler's own formatter prints the empty effect set everywhere else.
    assert(page(pages, "Wrap.md").contains("`type Aef: Eff = Pure`"), page(pages, "Wrap.md"))
  }

  test("doc.headings.01") {
    // A page owns `#` and `##`. A heading written in a comment must not sit alongside them.
    val pages = document(
      """
        |mod Api {
        |    ///
        |    /// Returns one.
        |    ///
        |    /// ## Detail
        |    ///
        |    /// More.
        |    ///
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    val md = page(pages, "Api.md")
    assert(md.contains("#### Detail"), md)
    assert(!md.contains("\n## Detail"), s"a comment heading competes with a generated section:\n$md")
  }

  test("doc.headings.02") {
    // Inside a fence a hash is content, not structure, and must be left alone.
    val pages = document(
      """
        |mod Api {
        |    ///
        |    /// Returns one.
        |    ///
        |    /// ```
        |    /// # not a heading
        |    /// ```
        |    ///
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    assert(page(pages, "Api.md").contains("```\n# not a heading\n```"), page(pages, "Api.md"))
  }

  test("doc.summary.05") {
    // A thematic break is not prose and must not be joined onto the line above it.
    val pages = document(
      """
        |mod Api {
        |    ///
        |    /// Returns one.
        |    /// ---
        |    /// More.
        |    ///
        |    pub def one(): Int32 = 1
        |}
        |""".stripMargin)

    val md = page(pages, "Api.md")
    assert(md.contains("`def one(): Int32` — Returns one.\n"), md)
    assert(!md.contains("Returns one. ---"), md)
  }

  test("page.selected.01") {
    // Restricting to a package must restrict the pages, not just their contents.
    val input =
      """
        |mod Included {
        |    pub def f(): Int32 = 1
        |}
        |
        |mod Excluded {
        |    pub def g(): Int32 = 2
        |}
        |""".stripMargin

    val selected = PackageModules.Selected(Set(ca.uwaterloo.flix.language.ast.Symbol.mkModuleSym(List("Included"))))
    val pages = document(input, selected)

    assert(pages.contains("Included.md"))
    assert(!pages.contains("Excluded.md"), s"got: ${pages.keys.toList.sorted.mkString(", ")}")
  }

  test("run.stale.01") {
    // A page for code that no longer exists must not survive a regeneration: it is still readable,
    // and no longer reachable from the index, which is the worst of both.
    withTempDir { dir =>
      generate("pub enum Color { case Red }", dir)
      val colorPage = dir.resolve("doc").resolve("Color.md")
      assert(Files.exists(colorPage))

      generate("pub enum Shape { case Square }", dir)
      assert(Files.exists(dir.resolve("doc").resolve("Shape.md")))
      assert(!Files.exists(colorPage), "a page for a removed enum survived regeneration")
    }
  }

  test("run.stale.02") {
    // Only files this backend wrote may be deleted. Anything else in the directory is not ours.
    withTempDir { dir =>
      generate("pub enum Color { case Red }", dir)
      val handWritten = dir.resolve("doc").resolve("NOTES.md")
      Files.write(handWritten, "# Notes\n".getBytes(StandardCharsets.UTF_8))

      generate("pub enum Shape { case Square }", dir)
      assert(Files.exists(handWritten), "a file this backend did not write was deleted")
    }
  }

  test("run.encoding.01") {
    // The format itself uses an em dash and a middle dot, so the bytes on disk must be UTF-8
    // whatever the platform default charset happens to be.
    withTempDir { dir =>
      generate(
        """
          |mod Api {
          |    ///
          |    /// Returns one.
          |    ///
          |    pub def one(): Int32 = 1
          |}
          |""".stripMargin, dir)

      val bytes = Files.readAllBytes(dir.resolve("doc").resolve("Api.md"))
      val text = new String(bytes, StandardCharsets.UTF_8)
      assert(text.contains("`def one(): Int32` — Returns one."), text)
      // Round-tripping through UTF-8 must be lossless: a mis-encoded em dash becomes '?' or U+FFFD.
      assert(!text.contains("?"), "output contains U+003F replacement")
      assert(!text.contains("\uFFFD"), "output contains U+FFFD replacement")
    }
  }

  test("page.omission.struct.01") {
    val pages = document(
      """
        |pub struct Person[r] {
        |    name: String
        |}
        |""".stripMargin)

    // Structs are currently omitted by Documentor.build, so no Person.md page is generated.
    assert(!pages.contains("Person.md"), "struct Person should be omitted upstream by Documentor.build")
  }

  test("page.omission.restrictable_enum.01") {
    val pages = document(
      """
        |pub restrictable enum Color[s] {
        |    case Red,
        |    case Custom
        |}
        |
        |pub def anchor(): Int32 = 1
        |""".stripMargin)

    // Restrictable enums are currently omitted by Documentor.build, so no Color.md page is generated.
    assert(!pages.contains("Color.md"), "restrictable enum Color should be omitted upstream by Documentor.build")
  }

  test("page.source_attribution.user_list.01") {
    withTempDir { dir =>
      val listFile = dir.resolve("List.flix")
      Files.writeString(listFile, "pub def customUserDef(): Int32 = 42")
      implicit val flix: Flix = new Flix().setOptions(Options.TestWithLibNix.copy(outputPath = dir))
      flix.addFile(listFile)
      flix.check() match {
        case (Some(root), Nil) =>
          val pages = MarkdownDocumentor.documentAll(root, PackageModules.All)
          val md = page(pages, "index.md")
          assert(!md.contains("main/src/library/List.flix"), "User List.flix was misattributed as stdlib")
          assert(md.contains("List.flix"), "User List.flix should be attributed to its file path")
        case (_, errors) => fail(CompilationMessage.formatAll(errors)(Formatter.NoFormatter, None))
      }
    }
  }

  test("page.source_attribution.virtual_list.01") {
    implicit val flix: Flix = new Flix().setOptions(Options.TestWithLibNix)
    flix.addVirtualPath(Path.of("List.flix"), "pub def userVirtualDef(): Int32 = 42")
    flix.check() match {
      case (Some(root), Nil) =>
        val pages = MarkdownDocumentor.documentAll(root, PackageModules.All)
        assert(!page(pages, "index.md").contains("main/src/library/List.flix"),
          "A virtual user file must not be attributed to the Flix repository by its basename")
      case (_, errors) => fail(CompilationMessage.formatAll(errors)(Formatter.NoFormatter, None))
    }
  }

  test("page.source_attribution.collision.01") {
    withTempDir { dir =>
      val listFile = dir.resolve("List.flix")
      Files.writeString(listFile, "pub def userDef(): Int32 = 1")
      implicit val flix: Flix = new Flix().setOptions(Options.TestWithLibNix.copy(outputPath = dir))
      flix.addFile(listFile)
      flix.check() match {
        case (Some(root), Nil) =>
          val pages = MarkdownDocumentor.documentAll(root, PackageModules.All)
          val indexMd = page(pages, "index.md")
          // When multiple distinct inputs exist, no single-file attribution statement should be rendered
          assert(!indexMd.contains("main/src/library/List.flix"))
        case (_, errors) => fail(CompilationMessage.formatAll(errors)(Formatter.NoFormatter, None))
      }
    }
  }

  test("page.links.validation.01") {
    // Every link target `[text](target.md)` in generated pages must correspond to an actual page in the document set.
    val pages = document(
      """
        |pub trait Eq[a] {
        |    pub def eq(x: a, y: a): Bool
        |}
        |
        |pub enum Option[t] {
        |    case None
        |    case Some(t)
        |}
        |
        |pub enum Result[t, e] {
        |    case Ok(t)
        |    case Err(e)
        |}
        |
        |mod Math {
        |    pub def add(x: Int32): Int32 = x
        |}
        |""".stripMargin)

    val linkPattern = """\[[^\]]+\]\(([^)]+\.md)\)""".r
    for ((pageName, content) <- pages) {
      for (m <- linkPattern.findAllMatchIn(content)) {
        val target = m.group(1)
        assert(pages.contains(target), s"Page $pageName contains broken link to '$target'")
      }
    }
  }

  test("diagram.svg.01") {
    // A trait with a supertrait generates a standalone SVG diagram file reference.
    withTempDir { dir =>
      implicit val flix: Flix = new Flix().setOptions(Options.TestWithLibNix.copy(outputPath = dir))
      generate(
        """
          |pub trait Base[a] {
          |    pub def base(x: a): Bool
          |}
          |
          |pub trait Derived[a] with Base[a] {
          |    pub def derived(x: a): Bool
          |}
          |""".stripMargin, dir)

      val derivedMd = dir.resolve("doc").resolve("Derived.md")
      assert(Files.exists(derivedMd))
      val text = Files.readString(derivedMd, StandardCharsets.UTF_8)
      assert(text.contains("![Trait Hierarchy](diagrams/Derived.svg)"))

      val svgPath = dir.resolve("doc").resolve("diagrams").resolve("Derived.svg")
      assert(Files.exists(svgPath), "Standalone SVG diagram Derived.svg should exist")
      val svgText = Files.readString(svgPath, StandardCharsets.UTF_8)
      assert(svgText.contains("<!-- Generated by the Flix compiler. Do not edit. -->"))
      assert(svgText.contains("Base"))
      assert(svgText.contains("Derived"))

      val xml = scala.xml.XML.loadString(svgText)
      assert(xml.label == "svg", "Generated SVG must be valid XML with root tag <svg>")
    }
  }

  test("diagram.svg.02") {
    val pages = document(
      """
        |pub trait Base[a] {
        |    pub def base(x: a): Bool
        |}
        |
        |pub trait Derived[a] with Base[a] {
        |    pub def derived(x: a): Bool
        |}
        |""".stripMargin)

    assert(!page(pages, "Derived.md").contains("diagrams/Derived.svg"),
      "In-memory pages must not link to an SVG that was not materialized by Documentor.run")
  }
}
