/*
 * Copyright 2026 Werner Stein
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 */
package ca.uwaterloo.flix.language.phase.jvm.classes

import ca.uwaterloo.flix.api.Flix
import ca.uwaterloo.flix.language.ast.{JvmAst, Symbol}
import ca.uwaterloo.flix.language.jvm.{ClassDescs, JavaClasses}
import ca.uwaterloo.flix.language.phase.jvm.ClassMaker.Final.IsFinal
import ca.uwaterloo.flix.language.phase.jvm.ClassMaker.Visibility.{IsPrivate, IsPublic}
import ca.uwaterloo.flix.language.phase.jvm.ClassMaker.{ConstructorMethod, StaticConstructorMethod, StaticField, StaticMethod}
import ca.uwaterloo.flix.language.phase.jvm.Instructions.*
import ca.uwaterloo.flix.language.phase.jvm.{ClassMaker, Mangle, MethodTypeDescs}
import org.objectweb.asm.{MethodVisitor, Type}

import java.lang.constant.ClassDesc
import java.lang.constant.ConstantDescs.{CD_Class, CD_int}

/**
  * A real Java `enum` generated for an exported, data-free Flix enum: one constant per case, in
  * case-ordinal order, so a constant's Java `ordinal()` is its Flix case's ordinal.
  *
  * The class is named like the namespace class of the enum's companion module (`Mod.Color` for
  * `Mod.Color`), so Java reads `Color.Red` and `Color.parse(..)` off one class. When that module
  * exists, this class *is* its namespace class and carries its shims; `CodeGen` then generates no
  * separate `GenNamespace` class of the same name.
  */
object GenExportedEnum {

  /**
    * The methods every Java enum has, whether declared by `java.lang.Enum`, inherited from
    * `Object`, or generated alongside the constants. A companion export of the same name would
    * either fail to load or hide the inherited method from Java callers.
    */
  val MemberNames: Set[String] = Set(
    "values", "valueOf", "name", "ordinal", "compareTo", "getDeclaringClass", "describeConstable",
    "equals", "hashCode", "toString", "getClass", "notify", "notifyAll", "wait", "clone", "finalize"
  )

  /** Returns the Java enum class of the Flix enum `sym`. */
  def desc(sym: Symbol.EnumSym): ClassDesc = Mangle.namespaceFacadeDesc(companionNamespace(sym))

  /** Returns the namespace of `sym`'s companion module, whose namespace class this enum replaces. */
  def companionNamespace(sym: Symbol.EnumSym): List[String] = sym.namespace :+ sym.name

  /**
    * Returns the enum class for `constants`, ordered by ordinal, carrying the shims of `defs`, the
    * entry points of the companion module `ns`.
    */
  def genByteCode(ns: List[String], constants: List[String], defs: List[JvmAst.Def])(implicit root: JvmAst.Root, flix: Flix): Array[Byte] = {
    val desc = Mangle.namespaceFacadeDesc(ns)
    val cm = ClassMaker.mkEnumClass(desc)

    for (name <- constants) cm.mkEnumConstant(ConstantField(desc, name))
    cm.mkSyntheticStaticField(ValuesField(desc))
    cm.mkConstructor(Constructor(desc), IsPrivate, constructorIns(_))
    cm.mkStaticConstructor(StaticConstructorMethod(desc), staticConstructorIns(desc, constants)(_))
    cm.mkStaticMethod(ValuesMethod(desc), IsPublic, IsFinal, valuesIns(desc, constants)(_))
    cm.mkStaticMethod(ValueOfMethod(desc), IsPublic, IsFinal, valueOfIns(desc)(_))
    cm.mkSyntheticStaticMethod(OfOrdinalMethod(desc), ofOrdinalIns(desc)(_))
    GenNamespace.mkShims(cm, ns, defs)

    cm.closeClassMaker()
  }

  /**
    * Returns a sealed interface for an exported data-carrying enum, permitting one nested record
    * per case, named `caseNames` in ordinal order, and carrying the shims of `defs`, the entry
    * points of the companion module `ns`.
    *
    * Each case record is generated by `GenExportedProduct.genNestedByteCode`. Both sides declare
    * the nesting: javac reads `Shape.Circle` only if the interface lists the record in its
    * `InnerClasses` and the record names the interface as its outer class.
    */
  def genSealedByteCode(ns: List[String], caseNames: List[String], defs: List[JvmAst.Def])(implicit root: JvmAst.Root, flix: Flix): Array[Byte] = {
    val desc = Mangle.namespaceFacadeDesc(ns)
    val cm = ClassMaker.mkInterface(desc)
    for (name <- caseNames) {
      val caseClass = caseDesc(desc, name)
      cm.mkNestMember(caseClass)
      cm.mkPermittedSubclass(caseClass)
      cm.mkInnerClass(caseClass, desc, name)
    }
    GenNamespace.mkShims(cm, ns, defs)
    cm.closeClassMaker()
  }

  /** Returns the record class of the case `name` of the sealed interface `outer`. */
  def caseDesc(outer: ClassDesc, name: String): ClassDesc =
    ClassDesc.ofInternalName(ClassDescs.internalNameOf(outer) + Flix.Delimiter + name)

  /** The constant of `desc` at `ordinal`, for a shim converting a Flix case to it. */
  def OfOrdinalMethod(desc: ClassDesc): StaticMethod =
    StaticMethod(desc, "$ofOrdinal", MethodTypeDescs.mkDescriptor(CD_int)(desc))

  private def ConstantField(desc: ClassDesc, name: String): StaticField = StaticField(desc, name, desc)

  /** Every constant in ordinal order, read by [[OfOrdinalMethod]] without copying. */
  private def ValuesField(desc: ClassDesc): StaticField = StaticField(desc, "$VALUES", desc.arrayType())

  private def Constructor(desc: ClassDesc): ConstructorMethod = ConstructorMethod(desc, List(JavaClasses.String, CD_int))

  private val EnumConstructor: ConstructorMethod = ConstructorMethod(JavaClasses.Enum, List(JavaClasses.String, CD_int))

  private def ValuesMethod(desc: ClassDesc): StaticMethod =
    StaticMethod(desc, "values", MethodTypeDescs.mkDescriptor()(desc.arrayType()))

  private def ValueOfMethod(desc: ClassDesc): StaticMethod =
    StaticMethod(desc, "valueOf", MethodTypeDescs.mkDescriptor(JavaClasses.String)(desc))

  /** `super(name, ordinal)`, exactly as javac compiles an enum's constructor. */
  private def constructorIns(implicit mv: MethodVisitor): Unit = {
    thisLoad()
    ALOAD(1)
    ILOAD(2)
    INVOKESPECIAL(EnumConstructor)
    RETURN()
  }

  /** Creates every constant, then the array of all of them. */
  private def staticConstructorIns(desc: ClassDesc, constants: List[String])(implicit mv: MethodVisitor): Unit = {
    for ((name, ordinal) <- constants.zipWithIndex) {
      NEW(desc)
      DUP()
      pushString(name)
      pushInt(ordinal)
      INVOKESPECIAL(Constructor(desc))
      PUTSTATIC(ConstantField(desc, name))
    }
    newConstantArray(desc, constants)
    PUTSTATIC(ValuesField(desc))
    RETURN()
  }

  /** A fresh array on every call, as `values()` promises, so a caller cannot corrupt `$VALUES`. */
  private def valuesIns(desc: ClassDesc, constants: List[String])(implicit mv: MethodVisitor): Unit = {
    newConstantArray(desc, constants)
    ARETURN()
  }

  /** `(Color) Enum.valueOf(Color.class, name)` */
  private def valueOfIns(desc: ClassDesc)(implicit mv: MethodVisitor): Unit = {
    mv.visitLdcInsn(Type.getType(desc.descriptorString()))
    ALOAD(0)
    INVOKESTATIC(JavaClasses.Enum, "valueOf", MethodTypeDescs.mkDescriptor(CD_Class, JavaClasses.String)(JavaClasses.Enum))
    CHECKCAST(desc)
    ARETURN()
  }

  /** `$VALUES[ordinal]` */
  private def ofOrdinalIns(desc: ClassDesc)(implicit mv: MethodVisitor): Unit = {
    GETSTATIC(ValuesField(desc))
    ILOAD(0)
    xArrayLoad(desc)
    ARETURN()
  }

  private def newConstantArray(desc: ClassDesc, constants: List[String])(implicit mv: MethodVisitor): Unit = {
    pushInt(constants.length)
    ANEWARRAY(desc)
    for ((name, ordinal) <- constants.zipWithIndex) {
      DUP()
      pushInt(ordinal)
      GETSTATIC(ConstantField(desc, name))
      xArrayStore(desc)
    }
  }
}
