/*
 * Copyright 2026 Werner Stein
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ca.uwaterloo.flix.tools

import ca.uwaterloo.flix.api.Bootstrap
import org.scalatest.funsuite.AnyFunSuite

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}
import java.util.concurrent.{Executors, TimeUnit}
import scala.jdk.CollectionConverters._
import scala.util.Using

class TestDocCLI extends AnyFunSuite {

  private val ProjectPrefix = "flix-doc-cli-test-"

  private def runCliSubprocess(args: Array[String], projectDir: Path): (Int, String, String) = {
    val javaBin   = System.getProperty("java.home") + "/bin/java"
    val classpath = System.getProperty("java.class.path")
    val cmd       = List(javaBin, "-cp", classpath, "ca.uwaterloo.flix.Main") ++ args.toList

    val processBuilder = new ProcessBuilder(cmd.asJava)
    processBuilder.directory(projectDir.toFile)
    processBuilder.redirectErrorStream(false)

    val process = processBuilder.start()
    val pool    = Executors.newFixedThreadPool(2)

    @volatile var stdout = ""
    @volatile var stderr = ""

    val stdoutFuture = pool.submit(new Runnable {
      override def run(): Unit =
        stdout = new String(process.getInputStream.readAllBytes(), StandardCharsets.UTF_8)
    })
    val stderrFuture = pool.submit(new Runnable {
      override def run(): Unit =
        stderr = new String(process.getErrorStream.readAllBytes(), StandardCharsets.UTF_8)
    })

    val completed = process.waitFor(120, TimeUnit.SECONDS)
    if (!completed) {
      process.destroyForcibly()
      process.waitFor(5, TimeUnit.SECONDS)
    }
    pool.shutdown()
    pool.awaitTermination(5, TimeUnit.SECONDS)

    stdoutFuture.get()
    stderrFuture.get()

    if (!completed) {
      fail(s"Subprocess timed out after 120 seconds!\nCmd: ${cmd.mkString(" ")}\nCwd: $projectDir\nSTDOUT:\n$stdout\nSTDERR:\n$stderr")
    }

    (process.exitValue(), stdout, stderr)
  }

  private def withProject[A](body: Path => A): A = {
    val p = Files.createTempDirectory(ProjectPrefix)
    try {
      Bootstrap.init(p)(System.out)
      body(p)
    } finally {
      deleteRecursively(p)
    }
  }

  private def deleteRecursively(path: Path): Unit = {
    if (Files.isDirectory(path)) {
      Using(Files.list(path)) { stream =>
        stream.forEach(deleteRecursively)
      }
    }
    Files.deleteIfExists(path)
  }

  test("CLI E2E: flix doc --doc-format md generates Markdown documentation") {
    withProject { p =>
      Files.writeString(p.resolve("src/Main.flix"),
        """|/// A sample enum.
           |pub enum Color { case Red, case Blue }
           |pub def compute(): Int32 = 42
           |""".stripMargin)

      val (exitCode, stdout, stderr) = runCliSubprocess(Array("doc", "--doc-format", "md"), p)
      assert(exitCode == 0, s"Expected exit 0, got $exitCode.\nSTDERR:\n$stderr\nSTDOUT:\n$stdout")

      val docDir = p.resolve("build/doc")
      val indexMd = docDir.resolve("index.md")
      val colorMd = docDir.resolve("Color.md")

      assert(Files.exists(indexMd), "build/doc/index.md should exist")
      assert(Files.exists(colorMd), "build/doc/Color.md should exist")

      val colorContent = Files.readString(colorMd, StandardCharsets.UTF_8)
      assert(colorContent.startsWith("<!-- Generated by the Flix compiler. Do not edit. -->"))
      assert(colorContent.contains("# Color"))
    }
  }

  test("CLI E2E: flix doc --doc-format all generates both HTML and Markdown documentation") {
    withProject { p =>
      Files.writeString(p.resolve("src/Main.flix"),
        """|pub enum Shape { case Circle, case Square }
           |""".stripMargin)

      val (exitCode, stdout, stderr) = runCliSubprocess(Array("doc", "--doc-format", "all"), p)
      assert(exitCode == 0, s"Expected exit 0, got $exitCode.\nSTDERR:\n$stderr\nSTDOUT:\n$stdout")

      val docDir = p.resolve("build/doc")
      assert(Files.exists(docDir.resolve("index.html")), "build/doc/index.html should exist")
      assert(Files.exists(docDir.resolve("index.md")), "build/doc/index.md should exist")
      assert(Files.exists(docDir.resolve("Shape.html")), "build/doc/Shape.html should exist")
      assert(Files.exists(docDir.resolve("Shape.md")), "build/doc/Shape.md should exist")
    }
  }

  test("CLI E2E: flix doc --doc-format all cleans stale generated HTML and Markdown files symmetrically") {
    withProject { p =>
      Files.writeString(p.resolve("src/Main.flix"),
        """|pub enum First { case A }
           |""".stripMargin)

      val (exitCode1, _, stderr1) = runCliSubprocess(Array("doc", "--doc-format", "all"), p)
      assert(exitCode1 == 0, s"Expected exit 0, got $exitCode1.\nSTDERR:\n$stderr1")

      val docDir = p.resolve("build/doc")
      val firstMd = docDir.resolve("First.md")
      val firstHtml = docDir.resolve("First.html")
      val notesFile = docDir.resolve("NOTES.txt")
      val handWrittenHtml = docDir.resolve("NOTES.html")

      assert(Files.exists(firstMd))
      assert(Files.exists(firstHtml))
      Files.writeString(notesFile, "User hand-written notes")
      Files.writeString(handWrittenHtml, "<h1>Custom User Page</h1>")

      // Change code to remove First and add Second
      Files.writeString(p.resolve("src/Main.flix"),
        """|pub enum Second { case B }
           |""".stripMargin)

      val (exitCode2, _, stderr2) = runCliSubprocess(Array("doc", "--doc-format", "all"), p)
      assert(exitCode2 == 0, s"Expected exit 0, got $exitCode2.\nSTDERR:\n$stderr2")

      assert(!Files.exists(firstMd), "Stale generated page First.md should be deleted")
      assert(!Files.exists(firstHtml), "Stale generated page First.html should be deleted")
      assert(Files.exists(docDir.resolve("Second.md")), "Newly generated page Second.md should exist")
      assert(Files.exists(docDir.resolve("Second.html")), "Newly generated page Second.html should exist")
      assert(Files.exists(notesFile), "Non-generated user file NOTES.txt should be preserved")
      assert(Files.exists(handWrittenHtml), "Non-generated user file NOTES.html without marker should be preserved")
    }
  }

  test("CLI E2E negative: invalid --doc-format option exits with non-zero exit code") {
    withProject { p =>
      Files.writeString(p.resolve("src/Main.flix"), "pub def f(): Int32 = 1")
      val (exitCode, stdout, stderr) = runCliSubprocess(Array("doc", "--doc-format", "invalid-format"), p)
      assert(exitCode != 0, "Invalid doc-format option should fail")
    }
  }

  test("CLI E2E negative: compilation errors in project exit with non-zero exit code") {
    withProject { p =>
      Files.writeString(p.resolve("src/Main.flix"), "pub def f(): Int32 = \"type-error\" + 42")
      val (exitCode, stdout, stderr) = runCliSubprocess(Array("doc", "--doc-format", "md"), p)
      assert(exitCode != 0, "Compilation errors should cause flix doc to exit with non-zero code")
    }
  }
}
