name: Community Build

on:
  pull_request:
  merge_group:
  push:
    branches: [develop]

permissions:
  contents: read

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: community-build-${{ github.ref }}

jobs:
  # Build the JAR once for all the community builds
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Install JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Mill and Coursier
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.cache/coursier
            ~/.cache/mill
          key: ${{ runner.os }}-mill-${{ hashFiles('build.mill', '.mill-version') }}
          restore-keys: |
            ${{ runner.os }}-mill-
      - name: Build Flix JAR
        run: ./mill flix.assembly
      - name: Upload Flix JAR
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: flix-jar
          path: out/flix/assembly.dest/out.jar

  # Spawn a separate job per community build
  community-build:
    needs: build-jar
    strategy:
      # collect all the failures
      fail-fast: false
      matrix:
        repo:
          - "flix/chalk"
          - "flix/datalog2"
          - "flix/test-pkg-trust-plain"
          - "flix/test-pkg-trust-unchecked-cast"
          - "JonathanStarup/Flix-ANSI-Terminal"
          - "JonathanStarup/ListSet"
          - "JonathanStarup/talpin1992-in-flix"
          - "magnus-madsen/bibblitz"
          - "jaschdoc/flix-test-pkg-trust-transitive-plain"
          - "jaschdoc/flix-test-pkg-trust-transitive-java"
          - "mlutze/flix-json"
          - "mlutze/flixball"
          - "rywiese/scope-graphs"
          - "stephentetley/flix-htmldoc"
          - "stephentetley/flix-pretty"
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check out project head
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          repository: ${{ matrix.repo }}
      - name: Download Flix JAR
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: flix-jar
      - name: Build community project
        timeout-minutes: 10
        run: |
          # Build the project.
          java -jar out.jar build --github-token ${{ secrets.GITHUB_TOKEN }}
