name: Community Build

on:
  pull_request:
  merge_group:
  push:
    branches: [master]

permissions:
  contents: read

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: community-build-${{ github.ref }}

jobs:
  # Build the JAR once for all the community builds
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Install JDK
        uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Mill and Coursier
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cache/coursier
            ~/.cache/mill
          key: ${{ runner.os }}-mill-${{ hashFiles('build.mill', '.mill-version') }}
          restore-keys: |
            ${{ runner.os }}-mill-
      - name: Build Flix JAR
        run: ./mill flix.assembly
      - name: Upload Flix JAR
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: flix-jar
          path: out/flix/assembly.dest/out.jar

  # Spawn a separate job per community build
  community-build:
    needs: build-jar
    strategy:
      # collect all the failures
      fail-fast: false
      matrix:
        repo:
          - "flix/chalk"
          - "flix/datalog2"
          - "flix/test-pkg-trust-plain"
          - "flix/test-pkg-trust-unchecked-cast"
          - "JonathanStarup/Flix-ANSI-Terminal"
          - "JonathanStarup/ListSet"
          - "JonathanStarup/talpin1992-in-flix"
          - "magnus-madsen/bibblitz"
          - "jaschdoc/flix-test-pkg-trust-transitive-plain"
          - "jaschdoc/flix-test-pkg-trust-transitive-java"
          - "mlutze/flix-json"
          - "mlutze/flixball"
          - "rywiese/scope-graphs"
          - "stephentetley/flix-htmldoc"
          - "stephentetley/flix-pretty"
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK
        uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check out project head
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          repository: ${{ matrix.repo }}
      - name: Download Flix JAR
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: flix-jar
      - name: Build community project
        timeout-minutes: 10
        run: |
          # Build the project.
          java -jar out.jar build --github-token ${{ secrets.GITHUB_TOKEN }}
